### PR TITLE
 GoLikeHeaders.set() logic improvements

### PR DESCRIPTION
**Pull request by paulfelix**

### CODE REVIEW

**Comment by denismakogon** [comment]
Seems like CI is configured to run on PRs from forks, I'll run tests locally and will let you know.

**Comment by paulfelix** [comment]
@denismakogon, looks like you will need to merge it.

**Comment by denismakogon** [comment]
I'm in the process of running tests. But, yeah, i'll do that ASAP.

**Comment by denismakogon** [comment]
Ok, finally got back. It works, thanks. Will release new fdk soon.

**Pull request merged**
