### PR TITLE
WIP: stdlib fdk experiment

### PR DESCRIPTION
**Pull request by rdallman**
note: this is totally a toy and doesn't implement an fdk interface, this just
sets out to talk the fn http unix socket protocol to see if it's possible to
do without a bunch of libraries. if this is possible, it's not much of a
stretch to add an interface around all this, I'm just not good at python and
will let somebody else do that probably.

this uses stdlib methods to make a unix socket server and serve http requests
this took a few hours to throw together after reading the stdlib docs and
searching for examples. got it returning a 200 anyway, so I mean think this
thing is okay for our purposes honestly? we don't need a robust http server
for this thing at all.

### CODE REVIEW

**Comment by rdallman** [comment]
@denismakogon let me know if/why this is a bad idea, but it seems pretty straightforward. would like to debug print requests from that handler really to see why things aren't linking up, but the pieces of the puzzle seem to all be there... I just can't get an exception out of it to see why I get an EOF right now :)

**Comment by denismakogon** [comment]
going to close this in favour of better option in #60

**Comment by rdallman** [comment]
no, not what i meant - sorry. the dockerfile is just broke here is all (on master), tiny pr

**Comment by denismakogon** [comment]
Please don’t, those dockerfile was will go away with #61

**Comment by rdallman** [comment]
roger

**Comment by denismakogon** [comment]
Thank you. Can you please review #60 #61 #62?

**Comment by rdallman** [comment]
@denismakogon yea, i'll review first thing tomorrow - today was a bit busy, apologies

**Pull request closed without merging**
