### PR TITLE
changing request header fields in context to lower case

### PR DESCRIPTION
**Pull request by shreyagarge**
- Link to issue this resolves
 Python functions longer than 30 seconds were always failing.
 This was because of a case mismatch in the strings for the request headers.

### CODE REVIEW

**Comment by jan-g** [comment]
Note to reviewers: all headers lower-cased on the way into the dictionary

**Comment by jan-g** [comment]
(It's be nice if `headers.get` were case insensitive, but that's for another patch.)

**Comment by riconnon** [comment]
LGTM but let's get a review from @denismakogon

**Comment by denismakogon** [comment]
I'd like to see tests for the issue that is being outlined in PR description: 
`* Python functions longer than 30 seconds were always failing.`

**Comment by riconnon** [comment]
I suppose the other thing that would be nice would be some tests around the deadline feature which is what made us notice this.

**Comment by denismakogon** [comment]
> I suppose the other thing that would be nice would be some tests around the deadline feature which is what made us notice this.

@riconnon there are a couple of those, but they weren't failing because of the header case.

**Comment by denismakogon** [comment]
The best thing that we can do here is to add tests in CLI where a user attempts to run a function longer than, let's say 10 seconds (simple sleep function) when the timeout is 4.

**Comment by denismakogon** [comment]
I'm going to merge this, but I'd like to see these tests in CLI. @shreyagarge, @riconnon can we make it happen?

**Comment by riconnon** [comment]
I don't think tests for the FDK context behaviour belong in the CLI
Why can't we do these in the FDK tests?

**Comment by denismakogon** [comment]
because we had to mimic the CLI calls in FDK tests, which is not necessary when the CLI already has boilerplate tests, i.e., everything that we need.

**Comment by riconnon** [comment]
but CLI tests cannot block merging to the FDK. Tests of FDK behaviour belong in the FDK.

**Comment by denismakogon** [comment]
than there's a need in a whole new stack of tests that none of the FDKs has so far.

**Comment by denismakogon** [comment]
Newer FDK Python v0.1.2 released.

**Pull request merged**
