### PR TITLE
Adding Anchore CI check

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by denismakogon** [comment]
One thing left - snyk token in order to enable CI checks.

**Comment by denismakogon** [comment]
@rdallman @carimura Yo. Finally, I made snyk checks green enough, so the CI is happy. The only thing I need is a release script to work which requires me to tweak CI config with our dockerhub user/passwords. If you know them - please DM me in slack.

**Comment by denismakogon** [comment]
Blocked-By: https://github.com/anchore/ci-tools/issues/10

**Comment by denismakogon** [comment]
Testing new Anchore orb 1.3.0 feature...

**Comment by denismakogon** [comment]
@rdallman I made image check jobs as scheduled ones, they suppose to run nightly, meaning there would be no per-commit image security checks.

**Comment by rdallman** [comment]
i do not know how to make 'build' step not required in circle here - possibly, we need to temporarily add a section named that that succeeds in order to get past CI, since we've removed it and it's still expecting a 'build' to run (we have 'test'/'deploy'/etc now)

**Comment by denismakogon** [comment]
> i do not know how to make 'build' step not required in circle here - possibly, we need to temporarily add a section named that that succeeds in order to get past CI, since we've removed it and it's still expecting a 'build' to run (we have 'test'/'deploy'/etc now)

it's in github repo configuration, i'll remove that.

**Comment by denismakogon** [comment]
> the other thing that comes to mind is how we're getting notified of this. I guess, we could probably hook into slack to notify when these fail? email could work too, but slack might be slightly less noisy / easier to manage once we have this set up for all images (probably, some cve will break them all), and broadcasts to everyone easier. we can do that separate too, probably, bringing up to discuss if you have any thoughts on it.

as far as i understand, Circle will notify the maintainers. At this moment, by email. But we can get slack push notifications using this tutorial: https://circleci.com/blog/slack-integration/

**Comment by rdallman** [comment]
> as far as i understand, Circle will notify the maintainers. At this moment, by email. But we can get slack push notifications using this tutorial: https://circleci.com/blog/slack-integration/

ok cool. fwiw I don't get any circle build emails right now, i'm not sure if this is an email setting on my personal settings or not, and I don't recall fiddling with it so it may be the default. want to get the slack integration set up?

**Pull request merged**
