### PR TITLE
Fix headers rendering

### LINKED ISSUE #37: How to set Content-type=application/json in response
I've tried to produce as response a JSON object, but using FDK content-type is always set to text/plain

I have tried using:
(1) simply a dictionary

    res = {}
    # res['apps'] = vet
    res['id'] = 100

    return res

(2) using response.RawResponse
with:

return response.RawResponse(
        ctx,
        status_code=200, 
        headers=[{"Content-Type":"application/json"}], 
        response_data=res
    )

but Content-type is not set to application/json

### PR DESCRIPTION
**Pull request by denismakogon**
Closes #37

### CODE REVIEW

**Comment by carimura** [comment]
@denismakogon thanks for this. Did it get a review?

**Comment by denismakogon** [comment]
Unfortunately, no one from our team doing a reviews in this repo from the very beginning.

To make sure this change works as expected, the change was tested with both unit and integration tests we have in this repo.

**Comment by carimura** [comment]
Ok. Please ensure that someone IS reviewing. Thank you.

cc @michael-w-williams @shaunsmith

**Comment by shaunsmith** [comment]
We need someone who speaks Python.

**Pull request merged**
