### PR TITLE
Cold start performance improvements

### PR DESCRIPTION
**Pull request by denismakogon**
- on a constraint infra, FDK backed by `aiohttp` becomes too slow on a cold start
 - FDK doesn't really use a lot from `aiohttp` expcet an HTTP request/response parsing

### CODE REVIEW

**Comment by zootalures** [comment]
Implementing an HTTP parser from scratch seems like over-kill here - is that definitely the right way of doing this?

**Comment by denismakogon** [comment]
@zootalures that's the same question we've (me and @jan-g) asked ourselves when we had `http` format. Both Pythons (2.X or 3.X) they don't have built-in HTTP parsers.
In our case, we have exactly 2 major requirements for a framework that provides an implementation of an HTTP server:
1. UDS transport binding support.
3. Supports async transport.
2. async/await support.

Nobody in Python's community (even Python core devs) though about making efficient async HTTP server for the environment with limit resources. So, we have exactly two options:
1. aiohttp (heavy requires at least 300Mb RAM to start within a second), flask(requires at least 240MB RAM, doesn't support UDS), django (requires at least 500Mb, doesn't support UDS), etc.
2. DYI HTTP parsing (we can do here whatever we want).

**Comment by denismakogon** [comment]
Here's a quote of one of the Python core developers (translated):
```
`asyncio` would never become an HTTP server, that's said, Python 3 doesn't async HTTP server. It was designed as an event loop for the TCP, SSL, UNIX sockets, pipes и subprocesses and streaming API. A web API was expressly extracted and now represented by `aiohttp`, soon it will become a part of standard library.
```
It means that if you'd like to make it better - do it by yourself, Python standard library would not help you with this.

**Comment by zootalures** [comment]
Can you explain why the Python FDK needs to be asynchronous?   I don't see this in other python FaaS platforms like lambda?

**Comment by denismakogon** [comment]
async nature of an FDK derived from the UDS transport API. 

Before Python 3 and it's async/await feature, underlying transport (socket, pipes, etc.) was synchronous, meaning, that with no additional tools that bring a certain level of the concurrency no matter what kind of a transport you'd use to build a networking application it would be synchronous. A good example here is `SimpleHTTP` server from Python 2 and `http.server` from Python 3 (both of these doesn't support transport definition, they use TCP socket by default, along with that they a notion: `is not recommended for production`).

So, why FDK suppose to be asynchronous-compatible - because underlying transport is asynchronous, in order to read the data from it you need to use coroutines (async/await feature).

That's said, in absence of a working solution in Python standard library and having a clear understanding that `aiohttp` is heavy and basically the number 2 option to go with, while the number 1 is the DIY HTTP server.

As a conclusion, we can't go forward with sync transport, because it will make the Python FDK work as WSGI server. Async transport is the only option. However, there is no HTTP server implementation for an async transport except `aiohttp`.


P.S.: you don't see it in lambda, because their RPC framework is concurrent, but you see a function handler only, you basically don't know about their internals.

**Comment by zootalures** [comment]
I'm not sure I understand- HTTP (at least in the FDK contract)  is basically synchronous : 

* Read request
* Process request  (run Function) 
* Render response

other FDKs (Ruby, Java for instance) don't have any asynchronous components.

**Comment by denismakogon** [comment]
In python that’s the only way to make this code stable and concurrent-ready. Even more, in Python you can run native concurrent http server, i.e., if it handles the requests it blocks for any incoming connections. So, you can’t do multiple calls to a function, only sequential calls.

Good you mentioned Node, in Node FDK you can do async futures. In Python, if an application doesn’t powered by an event loop there’s no safe way to make it work without killing current thread, don’t forget that python is single-threaded, again, there s no way to make bring sane concurrency level for the customer’s code without dealing with an event loop and asyncio specifically.

**Comment by zootalures** [comment]
Fn is not planning to support concurrent calls to functions at this time.

**Comment by denismakogon** [comment]
Even so, out of the box there’s no HTTP over UDS implementation in Python standard library with so necessary async API which is a MUST for hipster python apps.

**Comment by rdallman** [comment]
the issue last time was doing i/o over stdin/stdout with http and needing the whole thing encapsulated into one string to get it working instead of being able to implement the http framing parsing itself (I doubt it's impossible, I just remember getting hung up on this). I would hope that since we have a socket, libraries handle this? cursory google shows this is the case (not with async, as noted). what's wrong with WSGI if we're doing one function at a time (timeouts?)? users would still be able to add async stuff if they really wanted? what problems would this cause hipsters that isn't endemic of their relationship with their parents? in general fdks should be really as minimal as possible, we're just parsing input and output pretty much, not making a functions framework (at the fdk level) - is this true of the python fdk as it is or as is proposed?

**Comment by denismakogon** [comment]
> What's wrong with WSGI if we're doing one function at a time (timeouts?)? users would still be able to add async stuff if they really wanted?

Unfortunately, developers can't do async code inside of sync code block without blocking current thread (i.e., if you'd start an event in main thread you'd block any other thread from being executed until that moment when an event loop will complete all the coroutines in it.

> I would hope that since we have a socket, libraries handle this? cursory google shows this is the case (not with async, as noted). 

that's why i used `aiohttp` because it gave us all we need (UDS support, async/await, async transport, etc.). No way that we could go with sync HTTP server because it would become a hell of a nightmare to FDK customers who'd like to use all features of Python 3.7+, unfortunately.

When you run code within the current event loop there's no easy way to face with IO blocking (IO operation is a switcher for Python's GIL), basically, IO event in an event loop has different locking mechanism comparing to IO operation within main thread.

> in general fdks should be really as minimal as possible, we're just parsing input and output pretty much

That's what python FDK is no matter with this PR or whatever is in master branch. Unfortunately, if we'd like to speed up cold start we (i, personally) need to use faster tools, even if i'd have to develop my own HTTP request/response parsers on top of the asyncio event loop.

**Comment by rdallman** [comment]
i see stdlib can do unix socket and http parsing, and maybe I am really just not understanding why we can't just use those things since we're only running one function at a time? are there specific use cases you could outline that would help me understand, if you'll humor me? my understanding is that fdks are pretty much by definition an event loop, and a lot of this smells like we're making things more complicated than they need to be (and maybe they _do_ need to be, sorry to make you reiterate)

**Comment by denismakogon** [comment]
That’s only about running one function at the time. It’s all about programming model in Python specifically. One major issue of python has to be taking into account: as a developer you can’t run more than one thread in parallel.

An asyncio lib is a great problem-solver, with that you can start a multiple non-blocking operations at the same time, “almost” in parallel. In order to make it work you need at least 2 things: an event loop implementation, async/await API.

Why we can’t use sync HTTP parsers from stdlib? Well, the answer is simple - you throw away 8 years of python 3.x development by saying FDK supports only sync code. 

More technical (rather than personal) answer: sync mode disables background operations during request processing. 

Example: my function talks to multiple data feeds, one of the feeds may be not stable in terms of the connectivity, but you know how to retry on failures, so, as a developer I’d like to obtain the data over stable connection from that feed through the concurrent future while the rest of the code working with other feeds with stable connections (consider feeds here as DB, MQ, RSS, etc.)

You may think, okay, I can do threads and thread pool for simple thread synchorounisation. But here’s the most awful thing about Python: even thread pools are sync, zero, like literally, zero ways to do a concurrent operations in Python. Okay, maybe not threads, are there any concurrent features? - No, that’s why projects like eventlet, greenlet, tornado, gevent exist for python 2. 

That’s why Python 2 failed as a programming language. That’s why Python 3 is a successor with its event loop that allows to run concurrent futures in parallel, where each future is a async/await-based class or function, etc.

However, Python cores didn’t agree on which features suppose to be included in async HTTP server in stdlib, that’s why it lives as a separate project, known as - aiohttp.

**Comment by rdallman** [comment]
I think i'm really missing some context here, sorry. so even though we don't really need an async transport, since we're handling one request at a time and don't need retries, timeouts, etc, we still need to use aiohttp or write our own because using the standard library functions to accept on a socket and parse an http request will prevent users from using async threads in their code?

**Comment by rdallman** [comment]
I started playing with this idea here: https://github.com/fnproject/fdk-python/pull/59 in an attempt to understand. I guess, I still don't understand, but maybe explanations will make more sense to me now.

**Comment by denismakogon** [comment]
Once again. I'd like to state the following things:
1. async/await syntax is a MUST thing in modern python development, without that Python is useless, anywhere, for anything.
2. Having a single-threaded server that is not capable to allow developers to run background tasks - is a HUGE shame.
3. the PR #59 uses code NOT RECOMMENDED for anyone this is in Python docs. Zero applications built on top of it.
4. the PR #59 maybe has less LOC, but unfortunately, it does nothing for supporting the widely accepted modern programming model of Python 3, without following modern Python techniques - FDK Python is useless.

Most of the people don't like custom HTTP parser I have in this PR. Fair enough. One good thing of this PR is a delayed import that I'm going to move to a separate PR.

In a meantime, I'm closing this PR in favour of `aiohttp` which is the best option, for now, no matter if that takes extra time to start. FYI Python was never designed to work blazingly fast within those constraints, it has a different purpose.

Making another decision in favour of things like #59 is wrong because as a developer you'd face with likely unexpected concurrency problems within a function (not an FDK) as I mentioned before (having an ability to run async background operations within a function processing is a MUST feature which is available only with async/await feature).

**Comment by rdallman** [comment]
outlined here https://docs.python.org/3/library/socketserver.html seem to be some ways to `fork()` or use a `ThreadingXxx` server, but we are only processing one request at a time, so it didn't really seem relevant? anyway, seems like there's workarounds, I'm just not much of a pythonista really.

**Comment by denismakogon** [comment]
> so honestly saw this but I really think it's fine for our requirements? 

the code that is in #59 doesn't fit our requirements, because it doesn't allow to run background tasks based on async/await features of Python 3.5+.

> we're not using extensive http features at this time at least, is there any other reason for hesitation here aside from security?

yes, the absence of async/await feature support.

> perhaps there are other dragons lurking?

that's not a dragon lurking, honestly, I'm not arguing for no reason, really, async/await feature and syntax is too important here, I see no way for us ignoring that, that is too expensive for us as for the young community.
 
> outlined here https://docs.python.org/3/library/socketserver.html seem to be some ways to fork() or use a ThreadingXxx server

None of the threading-based mechanisms works as it's being written about in Python, event loop is required here as much as possible.

**Comment by rdallman** [comment]
ok. i understand that async/await is blocked (but not how/why, digress digress), that seems to be the only hang up then. any links to help me understand would be appreciated, but will probably seek out other opinions and try to see what lambda and company does.

**Comment by rdallman** [comment]
https://docs.python.org/3/library/asyncio-stream.html seems to be another option, but not immediately sure how to wire this up to the actual basehttprequesthandler thing (am not good at this)

**Comment by denismakogon** [comment]
I was playing around with this through the whole day, it's not easy, unfortunately, you basically have to do some manual request parsing (at least separate request body from the rest of the request).

I'm looking at the alternative right now, will see if that is better.

**Comment by rdallman** [comment]
yea, seems that way. I've found https://medium.com/@pgjones/an-asyncio-socket-tutorial-5e6f3308b8b0 which seems similarly discouraging, but is pretty useful post. gonna hunt around the standard library for some http bits and suppress my anger towards dynamic typing (and py docs don't seem to be very good about saying what type things are all the time, either, but anyway)... 

i'm thinking it may be possible to munge the basehttprequesthandler thing or something like it in the stdlib into something capable of being a streamreader/writer (I think that's what we need), or at least we have to implement asyncio.Protocol it seems

**Comment by rdallman** [comment]
are there any strong feelings about https://pypi.org/project/h11/ ? the page itself is a bit endearing, and I think reiterates a lot of what you've stated here already. that being said, it's 800 LOC to do the http basics with 0 3rd party dependencies, which is honestly exactly what we need (and it's a shame something like it doesn't seem to exist in the standard library and we're not alone in thinking that)

**Comment by zootalures** [comment]
None from me so long as we feel like we trust it and it fits license requirements  - Java ended up doing something similar  (using the Apache HTTP commons client library)

**Comment by zootalures** [comment]
I feel warm and fuzzy when above are handled by code that is a frequent attack surface, less so otherwise.

**Comment by denismakogon** [comment]
So, there are not so many options:
1. safe aiohttp (but we don't like it, because it's heavy to start within 5 seconds).
2. asyncio protocols API with h11.
3. DIY HTTP parser.

Honestly, i'd rather leave aiohttp for the sake of the community support and issue tracking.

**Comment by rdallman** [comment]
between 2 and 3 I guess I'd take 2, 3 is similarly 'asyncio with DIY HTTP Parser', and h11 is really just a parser, it's not bringing a lot of extra baggage (like aiohttp). noted about 1, I'd say in general we need an extremely limited feature set and community support hopefully doesn't matter so much here, this is hopefully a land this dependency and leave it forever kind of situation (HTTP/1.1 isn't going to change), and we shouldn't be exposing any of this to end-users. h11 is at least io-agnostic, should python at large decide to change their io model it should be pretty easy for us to swap in at that point with few changes. maybe these estimations are wrong, I've never been paid to write python and am not familiar with the community myself.

**Comment by denismakogon** [comment]
One thing that is a problem, for now, is an ability to run coroutines within the asyncio protocol API.

**Comment by rdallman** [comment]
alright, I've got https://github.com/fnproject/fdk-python/pull/59/commits/03e2d75ddcaf06755547e933dffc7362c0785f32 updated and ready to jeer at, put a bunch of words on the commit to read I won't regurgitate here...

**Comment by denismakogon** [comment]
Because nobody take Python seriously, nobody doing things more complex that hello-world. But I care personally about us letting people use whatever constructions they want within the FaaS.

Personally I’ve been using async/await features in Fn since the very beginning because there are so many libraries that migrated to asyncio, these libraries provide faster and more reliable API. Almost every major python project that deals with networking migrated to asyncio because that’s the ONLY way to do the IO right with Python 3.

There might be a reason why people don’t do async stuff in Python, because they don’t care about performance and IO-bound locking because of the GIL. 

Another thing is, at this moment most of python developers are data scientists - they do math, but not programming, they don’t care about python, they care about math.


The major reason why this convo happens here is that in other FDKs you can do async programming without FDK support (goroutines, JVM threads, node futures, etc.). In Python FDK the underlying technology suppose to be native to an event loop in order to provide necessary high-level API, for the customer’s code. That’s I stand on asyncio and event loop, once again, without support of these technologies FDK is useless for networking operations (i.e., customer’s code would be slow and synchronous on IO).

**Comment by denismakogon** [comment]
I just googled it “asyncio AWS lambda”. You’re going to see like 10-20 link related to running async code in lambda. So, it’s there, just out of curious, maybe you haven’t seen that because you haven’t tried?

**Comment by rdallman** [comment]
think Owen was just saying that none of the other cloud vendors seem to support it - actually seems to be true, nobody else seems to support async i/o for python. i've had trouble sussing out why we have to do async i/o just so that the user can use async features in their code (this is some language level issue I'm not grokking I guess). i see no reason our i/o can't be synchronous in this use case, am glad to be proven wrong on this I may be missing something but I'm really not seeing it: I think about this in any language and think we could have completely synchronous i/o for the fdk use case. i haven't gotten a direct answer maybe to that question, which would be, if we do synchronous i/o can a user still use async/await features? (I get the impression the answer is no, but that's really been my question all along)

**Comment by rdallman** [comment]
that being said, latest on #59 with h11 really seems like it's more than just a workable hack and seems like a relatively viable solution, where it seems like almost everybody is happy (except for coroutines maybe? i'm unclear on this, maybe it's a bigger issue than it seems)

**Comment by denismakogon** [comment]
My answer here is: within the sync IO you can’t do async operations, you can’t work with the event loop, you can’t work with corotuines, i.e., you can’t start sync unix server (from socketserver) and run an event loop in it, without blocking the whole application.

**Pull request closed without merging**
