### PR TITLE
Asyncio h11 (was #60)

### PR DESCRIPTION
**Pull request by rdallman**
this is a copy of #60 except rebased off of master and removes the commit from #62 so that this is only the change to h11. we can work off of this to drive h11 to completion without having the delayed import changes muddied in here... @denismakogon let me know if you have any preferences...

### CODE REVIEW

**Comment by rdallman** [comment]
@denismakogon fixing this up... i'm gonna try to fix up some comments from #60 here today too... will hand off EOD

**Comment by rdallman** [comment]
delayed import and h11 are separate features. that's fine, helps to communicate ;)

**Comment by denismakogon** [comment]
That’s why I wrote this twice in two different places: we need to merge code removal, then we need to merge delayed imports, then we replace aiohttp. That’s the most appropriate sequence of PR that need to be in master before making a release.

**Comment by rdallman** [comment]
sounds good, didn't know which parts you have been working on, let me know if/which I can help with... it's not clear about breaking changes yet for either of these patches still too

**Pull request closed without merging**
